version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: softdev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  be:
    build: ./be
    container_name: express-api
    depends_on:
      - db
    environment:
      - DOCKER_ENV=true   # 👈 tells backend it's running inside Docker
    ports:
      - "5000:5000"
    networks:
      - app-network

  fe:
    build: ./fe
    container_name: react-frontend
    depends_on:
      - be
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://express-api:5000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
